[[redirects]]
  from = "/21-legendary-legend!"
  to = "/21-legendary-legend"
[[redirects]]
  from = "/22-the-good-ol'-div-link"
  to = "/22-the-good-ol-div-link"
[[headers]]
  for = "/feed.xml"
  [headers.values]
  cache-control = '''
  max-age=86400,
  public='''
  must-revalidate='''